# Generated by Django 6.0.3 on 2026-04-19 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEntries',
            fields=[
                ('entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('Глюкоза', 'Глюкоза'), ('Терапия', 'Терапия'), ('Питание', 'Питание'), ('Физическая активность', 'Физическая активность'), ('Самочувствие', 'Самочувствие'), ('Дополнительные показатели', 'Дополнительные показатели')], max_length=40)),
                ('entry_datetime', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_monitoring_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitoring entry',
                'verbose_name_plural': 'Monitoring entries',
                'db_table': 'monitoring_entries',
            },
        ),
        migrations.CreateModel(
            name='ActivityEntries',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='activity_entry', serialize=False, to='monitoring.monitoringentries')),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_duration_min', models.IntegerField(blank=True, null=True)),
                ('activity_intensity', models.CharField(blank=True, choices=[('Низкая', 'Низкая'), ('Умеренная', 'Умеренная'), ('Высокая', 'Высокая')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'activity_entries',
            },
        ),
        migrations.CreateModel(
            name='GlucoseEntries',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='glucose_entry', serialize=False, to='monitoring.monitoringentries')),
                ('glucose_value_mmol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glucose_context', models.CharField(blank=True, choices=[('Натощак', 'Натощак'), ('До еды', 'До еды'), ('После еды', 'После еды'), ('Перед сном', 'Перед сном'), ('Ночью', 'Ночью'), ('Другое', 'Другое')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'glucose_entries',
            },
        ),
        migrations.CreateModel(
            name='MealEntries',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meal_entry', serialize=False, to='monitoring.monitoringentries')),
                ('meal_type', models.CharField(blank=True, choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин'), ('Перекус', 'Перекус'), ('Другое', 'Другое')], max_length=20, null=True)),
                ('meal_description', models.TextField(blank=True, null=True)),
                ('carbohydrates_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bread_units', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'meal_entries',
            },
        ),
        migrations.CreateModel(
            name='TherapyEntries',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='therapy_entry', serialize=False, to='monitoring.monitoringentries')),
                ('medication_name', models.CharField(max_length=150)),
                ('medication_category', models.CharField(blank=True, choices=[('Инсулин', 'Инсулин'), ('Сахароснижающий препарат', 'Сахароснижающий препарат'), ('Другое', 'Другое')], max_length=40, null=True)),
                ('dose_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dose_unit', models.CharField(blank=True, choices=[('ЕД', 'ЕД'), ('мг', 'мг'), ('мл', 'мл'), ('Таблетка', 'Таблетка'), ('Капсула', 'Капсула'), ('Другое', 'Другое')], max_length=20, null=True)),
                ('administration_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'therapy_entries',
            },
        ),
        migrations.CreateModel(
            name='VitalSignsEntries',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vital_signs_entry', serialize=False, to='monitoring.monitoringentries')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('pulse_bpm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vital_signs_entries',
            },
        ),
        migrations.CreateModel(
            name='WellbeingEntries',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wellbeing_entry', serialize=False, to='monitoring.monitoringentries')),
                ('wellbeing_type', models.CharField(choices=[('Гипогликемия', 'Гипогликемия'), ('Гипергликемия', 'Гипергликемия'), ('Стресс', 'Стресс'), ('Инфекция', 'Инфекция'), ('Нарушение сна', 'Нарушение сна'), ('Жалоба', 'Жалоба'), ('Другое', 'Другое')], max_length=30)),
                ('symptom_description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('Лёгкая', 'Лёгкая'), ('Умеренная', 'Умеренная'), ('Высокая', 'Высокая'), ('Критическая', 'Критическая')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'wellbeing_entries',
            },
        ),
        migrations.CreateModel(
            name='CriticalEvents',
            fields=[
                ('critical_event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Низкая глюкоза', 'Низкая глюкоза'), ('Высокая глюкоза', 'Высокая глюкоза'), ('Высокое АД', 'Высокое АД'), ('Низкое АД', 'Низкое АД'), ('Тахикардия', 'Тахикардия'), ('Брадикардия', 'Брадикардия'), ('Другое', 'Другое')], max_length=30)),
                ('severity', models.CharField(choices=[('Лёгкая', 'Лёгкая'), ('Умеренная', 'Умеренная'), ('Высокая', 'Высокая'), ('Критическая', 'Критическая')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Новое', 'Новое'), ('Подтверждено', 'Подтверждено'), ('Закрыто', 'Закрыто')], default='Новое', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_critical_events', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_events', to='monitoring.monitoringentries')),
            ],
            options={
                'verbose_name': 'Critical event',
                'verbose_name_plural': 'Critical events',
                'db_table': 'critical_events',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialty', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('Предупреждение', 'Предупреждение'), ('Оповещение врачу', 'Оповещение врачу'), ('Системное', 'Системное')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('critical_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='monitoring.criticalevents')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('diabetes_type', models.CharField(choices=[('СД 1 типа', 'СД 1 типа'), ('СД 2 типа', 'СД 2 типа'), ('Гестационный диабет', 'Гестационный диабет'), ('Предиабет', 'Предиабет'), ('Другое', 'Другое')], max_length=30)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='PatientDoctorAttachments',
            fields=[
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('В обработке', 'В обработке'), ('Подтвержденный', 'Подтвержденный'), ('Отклоненный', 'Отклоненный'), ('Отмененный', 'Отмененный'), ('Срок действия истек', 'Срок действия истек')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_attachments', to='monitoring.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_attachments', to='monitoring.patients')),
            ],
            options={
                'verbose_name': 'Patient-doctor attachment',
                'verbose_name_plural': 'Patient-doctor attachments',
                'db_table': 'patient_doctor_attachments',
            },
        ),
        migrations.AddField(
            model_name='monitoringentries',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='monitoring_entries', to='monitoring.patients'),
        ),
        migrations.AddIndex(
            model_name='criticalevents',
            index=models.Index(fields=['entry'], name='idx_critical_events_entry'),
        ),
        migrations.AddIndex(
            model_name='criticalevents',
            index=models.Index(fields=['status', '-detected_at'], name='idx_ce_status_dt'),
        ),
        migrations.AddIndex(
            model_name='doctors',
            index=models.Index(fields=['user'], name='idx_doctors_user'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['recipient_user', 'is_read'], name='idx_notif_user_read'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['user'], name='idx_patients_user'),
        ),
        migrations.AddIndex(
            model_name='patientdoctorattachments',
            index=models.Index(fields=['doctor', 'status'], name='idx_pda_doctor_status'),
        ),
        migrations.AddIndex(
            model_name='patientdoctorattachments',
            index=models.Index(fields=['patient', 'status'], name='idx_pda_patient_status'),
        ),
        migrations.AddConstraint(
            model_name='patientdoctorattachments',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'В обработке')), fields=('patient', 'doctor'), name='uniq_pda_patient_doctor_pending'),
        ),
        migrations.AddConstraint(
            model_name='patientdoctorattachments',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Подтвержденный')), fields=('patient', 'doctor'), name='uniq_pda_patient_doctor_confirmed'),
        ),
        migrations.AddIndex(
            model_name='monitoringentries',
            index=models.Index(fields=['patient', '-entry_datetime'], name='idx_me_patient_dt'),
        ),
        migrations.AddIndex(
            model_name='monitoringentries',
            index=models.Index(fields=['entry_type', '-entry_datetime'], name='idx_me_type_dt'),
        ),
        migrations.AddIndex(
            model_name='monitoringentries',
            index=models.Index(fields=['entered_by_user'], name='idx_me_entered_by'),
        ),
    ]
