# Generated by Django 6.0.3 on 2026-04-30 13:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activityentries',
            constraint=models.CheckConstraint(condition=models.Q(('activity_duration_min__isnull', True), models.Q(('activity_duration_min__gte', 1), ('activity_duration_min__lte', 1440)), _connector='OR'), name='chk_activity_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='glucoseentries',
            constraint=models.CheckConstraint(condition=models.Q(('glucose_value_mmol__gte', Decimal('0.1')), ('glucose_value_mmol__lte', Decimal('40'))), name='chk_glucose_value_range'),
        ),
        migrations.AddConstraint(
            model_name='mealentries',
            constraint=models.CheckConstraint(condition=models.Q(('carbohydrates_g__isnull', True), models.Q(('carbohydrates_g__gte', Decimal('0')), ('carbohydrates_g__lte', Decimal('1000'))), _connector='OR'), name='chk_meal_carbs_range'),
        ),
        migrations.AddConstraint(
            model_name='mealentries',
            constraint=models.CheckConstraint(condition=models.Q(('bread_units__isnull', True), models.Q(('bread_units__gte', Decimal('0')), ('bread_units__lte', Decimal('100'))), _connector='OR'), name='chk_meal_bu_range'),
        ),
        migrations.AddConstraint(
            model_name='therapyentries',
            constraint=models.CheckConstraint(condition=models.Q(('dose_amount__isnull', True), models.Q(('dose_amount__gte', Decimal('0')), ('dose_amount__lte', Decimal('100000'))), _connector='OR'), name='chk_therapy_dose_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsignsentries',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), models.Q(('weight_kg__gte', Decimal('1')), ('weight_kg__lte', Decimal('500'))), _connector='OR'), name='chk_vital_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsignsentries',
            constraint=models.CheckConstraint(condition=models.Q(('systolic_bp__isnull', True), models.Q(('systolic_bp__gte', 50), ('systolic_bp__lte', 300)), _connector='OR'), name='chk_vital_systolic_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsignsentries',
            constraint=models.CheckConstraint(condition=models.Q(('diastolic_bp__isnull', True), models.Q(('diastolic_bp__gte', 30), ('diastolic_bp__lte', 200)), _connector='OR'), name='chk_vital_diastolic_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsignsentries',
            constraint=models.CheckConstraint(condition=models.Q(('pulse_bpm__isnull', True), models.Q(('pulse_bpm__gte', 20), ('pulse_bpm__lte', 250)), _connector='OR'), name='chk_vital_pulse_range'),
        ),
    ]
